[project]
name = "android-auto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adbutils>=2.12.0",
    "av>=16.1.0",
    "certifi==2025.8.3",
    "cffi==1.17.1",
    "charset-normalizer==3.4.3",
    "click==8.2.1",
    "contourpy==1.3.3",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "deprecation==2.1.0",
    "filelock==3.19.1",
    "fonttools==4.59.2",
    "fsspec==2025.7.0",
    "idna==3.10",
    "jinja2==3.1.6",
    "kiwisolver==1.4.9",
    "lapx>=0.10.0",
    "loguru==0.7.3",
    "lxml==6.0.1",
    "markupsafe==3.0.2",
    "matplotlib==3.10.6",
    "moosegesture==1.0.2",
    "mpmath==1.3.0",
    "mysc>=3.3",
    "networkx==3.5",
    "numpy>=2.4.2",
    "opencv-python>=4.12.0",
    "opuslib==3.0.1",
    "packaging==25.0",
    "pillow==11.3.0",
    "polars==1.32.3",
    "psutil==7.0.0",
    "py-cpuinfo==9.0.0",
    "pyaudio==0.2.14",
    "pycparser==2.22",
    "pyflac==3.0.0",
    "pynput==1.8.1",
    "pyobjc-core==11.1",
    "pyobjc-framework-applicationservices==11.1",
    "pyobjc-framework-cocoa==11.1",
    "pyobjc-framework-coretext==11.1",
    "pyobjc-framework-quartz==11.1",
    "pyogg==0.6.14a1",
    "pyparsing==3.2.3",
    "pyperclip>=1.11.0",
    "python-dateutil==2.9.0.post0",
    "pyyaml==6.0.2",
    "requests==2.32.5",
    "retry2==0.9.5",
    "scipy==1.16.1",
    "setuptools==80.9.0",
    "six==1.17.0",
    "soundfile==0.13.1",
    "sympy==1.14.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "typing-extensions==4.15.0",
    "uiautomator2>=3.4.0",
    "ultralytics==8.3.189",
    "ultralytics-thop==2.0.16",
    "urllib3==2.5.0",
]
